import { Recipe } from '@/types';

export const RECIPES: Record<string, Recipe> = {

  // ─── MENU STANDARD — Entrées ─────────────────────────────────────────────

  'std-s1': {
    id: 'std-s1',
    title: 'Salade de quinoa',
    description: 'Quinoa, légumes grillés, vinaigrette citron',
    category: 'starter',
    prepTime: 15,
    cookTime: 15,
    servings: 10,
    difficulty: 'easy',
    orientations: ['GLUC-MOD', 'PROT-BON'],
    tags: ['végétarien', 'sans gluten', 'froid'],
    ingredients: [
      { name: 'Quinoa blanc', quantity: '500', unit: 'g' },
      { name: 'Courgette', quantity: '3' },
      { name: 'Poivron rouge', quantity: '2' },
      { name: 'Poivron jaune', quantity: '2' },
      { name: 'Tomates cerises', quantity: '300', unit: 'g' },
      { name: 'Concombre', quantity: '1' },
      { name: 'Persil frais', quantity: '1', unit: 'bouquet' },
      { name: 'Menthe fraîche', quantity: '10', unit: 'feuilles' },
      { name: 'Jus de citron', quantity: '3', unit: 'citrons' },
      { name: 'Huile d\'olive', quantity: '4', unit: 'c. à soupe' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Rincer le quinoa à l\'eau froide. Cuire dans 1 L d\'eau bouillante salée pendant 12 minutes. Égoutter et laisser refroidir.' },
      { order: 2, instruction: 'Couper les courgettes et poivrons en dés. Faire griller à feu vif avec un filet d\'huile d\'olive pendant 8-10 minutes. Saler, poivrer. Laisser refroidir.' },
      { order: 3, instruction: 'Couper les tomates cerises en deux. Épépiner et trancher le concombre.' },
      { order: 4, instruction: 'Préparer la vinaigrette : mélanger le jus des citrons, l\'huile d\'olive, sel et poivre.' },
      { order: 5, instruction: 'Dans un grand saladier, mélanger le quinoa refroidi, les légumes grillés, les tomates et le concombre.' },
      { order: 6, instruction: 'Ajouter le persil et la menthe ciselés. Verser la vinaigrette et mélanger délicatement. Rectifier l\'assaisonnement.' },
      { order: 7, instruction: 'Réserver au frais jusqu\'au service. Peut se préparer la veille.' },
    ],
    nutrition: { calories: 185, protein: 7, carbs: 28, fat: 6, fiber: 4 },
  },

  'std-s2': {
    id: 'std-s2',
    title: 'Velouté de potiron',
    description: 'Courge butternut, noix de muscade, crème légère',
    category: 'starter',
    prepTime: 20,
    cookTime: 30,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'GLUC-MOD'],
    tags: ['végétarien', 'sans gluten', 'chaud'],
    ingredients: [
      { name: 'Courge butternut', quantity: '3', unit: 'kg' },
      { name: 'Oignons', quantity: '3' },
      { name: 'Ail', quantity: '4', unit: 'gousses' },
      { name: 'Bouillon de légumes', quantity: '2', unit: 'L' },
      { name: 'Crème légère 15%', quantity: '200', unit: 'ml' },
      { name: 'Noix de muscade', quantity: '1', unit: 'c. à café' },
      { name: 'Gingembre frais', quantity: '20', unit: 'g' },
      { name: 'Huile d\'olive', quantity: '2', unit: 'c. à soupe' },
      { name: 'Sel, poivre blanc', quantity: 'q.s.' },
      { name: 'Graines de courge', quantity: '50', unit: 'g' },
    ],
    steps: [
      { order: 1, instruction: 'Éplucher et couper la courge butternut en gros cubes. Éplucher et émincer les oignons et l\'ail.' },
      { order: 2, instruction: 'Dans une grande cocotte, faire revenir les oignons dans l\'huile d\'olive à feu moyen pendant 5 minutes. Ajouter l\'ail et le gingembre râpé.' },
      { order: 3, instruction: 'Ajouter les cubes de courge et faire revenir 3 minutes en remuant.' },
      { order: 4, instruction: 'Verser le bouillon chaud. Porter à ébullition, puis réduire à feu doux et cuire 25 minutes jusqu\'à ce que la courge soit tendre.' },
      { order: 5, instruction: 'Mixer finement avec un mixeur plongeant. Incorporer la crème légère. Assaisonner avec la muscade, sel et poivre.' },
      { order: 6, instruction: 'Réchauffer si nécessaire sans bouillir. Servir dans des bols avec quelques graines de courge torréfiées.' },
    ],
    nutrition: { calories: 120, protein: 3, carbs: 18, fat: 4, fiber: 3 },
  },

  'std-s3': {
    id: 'std-s3',
    title: 'Carpaccio de betterave',
    description: 'Betterave rôtie, chèvre frais, graines de tournesol',
    category: 'starter',
    prepTime: 15,
    cookTime: 60,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'ANTIOXYDANT'],
    tags: ['végétarien', 'sans gluten', 'froid'],
    ingredients: [
      { name: 'Betteraves crues', quantity: '2', unit: 'kg' },
      { name: 'Chèvre frais', quantity: '300', unit: 'g' },
      { name: 'Graines de tournesol', quantity: '100', unit: 'g' },
      { name: 'Roquette', quantity: '100', unit: 'g' },
      { name: 'Vinaigre balsamique', quantity: '3', unit: 'c. à soupe' },
      { name: 'Huile de noix', quantity: '3', unit: 'c. à soupe' },
      { name: 'Miel', quantity: '1', unit: 'c. à café' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Envelopper les betteraves entières dans du papier aluminium avec un filet d\'huile. Cuire au four à 200°C pendant 60 minutes. Laisser refroidir.' },
      { order: 2, instruction: 'Éplucher les betteraves refroidies (utiliser des gants). Trancher très finement à la mandoline ou au couteau.' },
      { order: 3, instruction: 'Torréfier les graines de tournesol à sec dans une poêle 3 minutes. Réserver.' },
      { order: 4, instruction: 'Préparer la vinaigrette : fouetter le vinaigre balsamique, l\'huile de noix, le miel, sel et poivre.' },
      { order: 5, instruction: 'Disposer les tranches de betterave en rosace sur chaque assiette. Ajouter des brisures de chèvre frais et quelques feuilles de roquette.' },
      { order: 6, instruction: 'Parsemer de graines de tournesol et arroser de vinaigrette au moment du service.' },
    ],
    nutrition: { calories: 155, protein: 8, carbs: 14, fat: 8, fiber: 3 },
  },

  // ─── MENU STANDARD — Plats ───────────────────────────────────────────────

  'std-m1': {
    id: 'std-m1',
    title: 'Poulet rôti patates douces',
    description: 'Filet de poulet fermier, patates douces rôties, haricots verts',
    category: 'main',
    prepTime: 20,
    cookTime: 35,
    servings: 10,
    difficulty: 'easy',
    orientations: ['PROT-BON', 'GLUC-MOD', 'VIANDE-BLANCHE'],
    tags: ['sans gluten', 'haute protéine', 'chaud'],
    ingredients: [
      { name: 'Filets de poulet fermier', quantity: '2', unit: 'kg' },
      { name: 'Patates douces', quantity: '2', unit: 'kg' },
      { name: 'Haricots verts', quantity: '1', unit: 'kg' },
      { name: 'Ail', quantity: '6', unit: 'gousses' },
      { name: 'Romarin frais', quantity: '4', unit: 'branches' },
      { name: 'Thym frais', quantity: '4', unit: 'branches' },
      { name: 'Huile d\'olive', quantity: '4', unit: 'c. à soupe' },
      { name: 'Jus de citron', quantity: '2', unit: 'citrons' },
      { name: 'Paprika doux', quantity: '2', unit: 'c. à café' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Préchauffer le four à 200°C. Éplucher les patates douces et les couper en cubes de 2 cm.' },
      { order: 2, instruction: 'Mélanger les cubes de patates douces avec 2 c. à soupe d\'huile d\'olive, sel, poivre et paprika. Disposer sur une plaque et enfourner 25 minutes.' },
      { order: 3, instruction: 'Inciser les filets de poulet et y glisser des tranches d\'ail et du thym. Badigeonner avec le reste d\'huile, jus de citron et romarin.' },
      { order: 4, instruction: 'Faire dorer les filets à la poêle 3 minutes de chaque côté, puis terminer au four à 180°C pendant 15 minutes.' },
      { order: 5, instruction: 'Équeueter les haricots verts. Les cuire à la vapeur ou à l\'eau bouillante salée pendant 8 minutes. Ils doivent rester légèrement croquants.' },
      { order: 6, instruction: 'Reposer le poulet 5 minutes avant de le trancher. Servir avec les patates douces et les haricots verts.' },
    ],
    nutrition: { calories: 410, protein: 48, carbs: 35, fat: 9, fiber: 6 },
  },

  'std-m2': {
    id: 'std-m2',
    title: 'Saumon grillé riz complet',
    description: 'Pavé de saumon, riz complet, brocolis vapeur',
    category: 'main',
    prepTime: 10,
    cookTime: 30,
    servings: 10,
    difficulty: 'easy',
    orientations: ['PROT-BON', 'ANTI-INFLAM', 'GLUC-MOD'],
    tags: ['sans gluten', 'oméga-3', 'chaud'],
    ingredients: [
      { name: 'Pavés de saumon (150g/pers)', quantity: '1.5', unit: 'kg' },
      { name: 'Riz complet', quantity: '800', unit: 'g' },
      { name: 'Brocolis', quantity: '2', unit: 'kg' },
      { name: 'Citron', quantity: '3' },
      { name: 'Aneth frais', quantity: '1', unit: 'bouquet' },
      { name: 'Ail', quantity: '4', unit: 'gousses' },
      { name: 'Huile d\'olive', quantity: '3', unit: 'c. à soupe' },
      { name: 'Sauce soja légère', quantity: '2', unit: 'c. à soupe' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Rincer le riz complet. Cuire dans 2 fois son volume d\'eau salée pendant 30 minutes à feu doux. Réserver au chaud.' },
      { order: 2, instruction: 'Couper les brocolis en fleurettes. Cuire à la vapeur 8 minutes. Ils doivent rester fermes et verts. Réserver.' },
      { order: 3, instruction: 'Mélanger la sauce soja, le jus d\'un citron, l\'ail haché et l\'huile d\'olive. Badigeonner les pavés de saumon.' },
      { order: 4, instruction: 'Chauffer une poêle grill à feu vif. Cuire les pavés côté peau 4 minutes, retourner et cuire 3 minutes. Le centre doit rester rosé.' },
      { order: 5, instruction: 'Servir le saumon sur le riz complet avec les brocolis. Arroser d\'un filet de citron et parsemer d\'aneth frais ciselé.' },
    ],
    nutrition: { calories: 480, protein: 42, carbs: 40, fat: 15, fiber: 5 },
  },

  'std-m3': {
    id: 'std-m3',
    title: 'Pâtes bolognaise sport',
    description: 'Pâtes semi-complètes, bœuf haché maigre, tomates fraîches',
    category: 'main',
    prepTime: 15,
    cookTime: 40,
    servings: 10,
    difficulty: 'easy',
    orientations: ['GLUC-HAUT', 'PROT-BON'],
    tags: ['haute énergie', 'chaud', 'classique'],
    ingredients: [
      { name: 'Pâtes semi-complètes (penne)', quantity: '1.2', unit: 'kg' },
      { name: 'Bœuf haché 5% MG', quantity: '1.5', unit: 'kg' },
      { name: 'Tomates concassées', quantity: '2', unit: 'boîtes 800g' },
      { name: 'Tomates fraîches', quantity: '500', unit: 'g' },
      { name: 'Oignons', quantity: '3' },
      { name: 'Ail', quantity: '5', unit: 'gousses' },
      { name: 'Carotte', quantity: '2' },
      { name: 'Céleri', quantity: '2', unit: 'branches' },
      { name: 'Concentré de tomates', quantity: '3', unit: 'c. à soupe' },
      { name: 'Basilic frais', quantity: '1', unit: 'bouquet' },
      { name: 'Parmesan allégé', quantity: '100', unit: 'g' },
      { name: 'Huile d\'olive', quantity: '2', unit: 'c. à soupe' },
      { name: 'Sel, poivre, origan', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Émincer finement les oignons, l\'ail, la carotte et le céleri. Les faire revenir dans l\'huile d\'olive à feu moyen pendant 8 minutes.' },
      { order: 2, instruction: 'Ajouter le bœuf haché, faire revenir à feu vif en émiettant. Cuire jusqu\'à ce que la viande soit bien dorée.' },
      { order: 3, instruction: 'Incorporer le concentré de tomates, les tomates concassées et les tomates fraîches coupées en dés. Assaisonner avec origan, sel et poivre.' },
      { order: 4, instruction: 'Laisser mijoter à feu doux pendant 25-30 minutes en remuant occasionnellement. La sauce doit épaissir.' },
      { order: 5, instruction: 'Cuire les pâtes al dente dans une grande quantité d\'eau bouillante salée, selon le temps indiqué sur le paquet moins 1 minute.' },
      { order: 6, instruction: 'Égoutter les pâtes en conservant une louche d\'eau de cuisson. Incorporer les pâtes à la sauce avec l\'eau de cuisson. Mélanger.' },
      { order: 7, instruction: 'Servir avec quelques feuilles de basilic frais et un peu de parmesan allégé râpé.' },
    ],
    nutrition: { calories: 560, protein: 45, carbs: 65, fat: 10, fiber: 7 },
  },

  // ─── MENU ANTI-INFLAM — Entrées ──────────────────────────────────────────

  'ai-s1': {
    id: 'ai-s1',
    title: 'Smoothie vert anti-inflammatoire',
    description: 'Épinards, concombre, gingembre, citron vert',
    category: 'starter',
    prepTime: 5,
    cookTime: 0,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM'],
    tags: ['végétalien', 'sans gluten', 'froid', 'récupération'],
    ingredients: [
      { name: 'Épinards frais', quantity: '600', unit: 'g' },
      { name: 'Concombre', quantity: '2' },
      { name: 'Pommes vertes', quantity: '4' },
      { name: 'Gingembre frais', quantity: '60', unit: 'g' },
      { name: 'Citrons verts', quantity: '4' },
      { name: 'Eau de coco', quantity: '1', unit: 'L' },
      { name: 'Curcuma en poudre', quantity: '2', unit: 'c. à café' },
      { name: 'Poivre noir', quantity: '1', unit: 'pincée' },
      { name: 'Glaçons', quantity: 'au goût' },
    ],
    steps: [
      { order: 1, instruction: 'Laver les épinards et le concombre. Épépiner et couper les pommes en quartiers.' },
      { order: 2, instruction: 'Éplucher et râper le gingembre. Presser les citrons verts.' },
      { order: 3, instruction: 'Mixer tous les ingrédients par petites portions avec l\'eau de coco jusqu\'à obtenir un mélange lisse.' },
      { order: 4, instruction: 'Ajouter le curcuma et une pincée de poivre noir (active les propriétés anti-inflammatoires de la curcumine).' },
      { order: 5, instruction: 'Servir immédiatement bien frais avec des glaçons.' },
    ],
    nutrition: { calories: 75, protein: 2, carbs: 14, fat: 1, fiber: 3 },
  },

  'ai-s2': {
    id: 'ai-s2',
    title: 'Tartare de thon',
    description: 'Thon frais, avocat, sésame, sauce soja légère',
    category: 'starter',
    prepTime: 20,
    cookTime: 0,
    servings: 10,
    difficulty: 'medium',
    orientations: ['ANTI-INFLAM', 'PROT-MAIGRE'],
    tags: ['sans gluten', 'cru', 'oméga-3', 'froid'],
    ingredients: [
      { name: 'Thon rouge frais', quantity: '1.2', unit: 'kg' },
      { name: 'Avocats mûrs', quantity: '5' },
      { name: 'Graines de sésame', quantity: '80', unit: 'g' },
      { name: 'Sauce soja légère', quantity: '60', unit: 'ml' },
      { name: 'Huile de sésame', quantity: '3', unit: 'c. à soupe' },
      { name: 'Jus de citron vert', quantity: '3', unit: 'citrons' },
      { name: 'Gingembre frais', quantity: '30', unit: 'g' },
      { name: 'Ciboulette', quantity: '1', unit: 'bouquet' },
      { name: 'Piment d\'Espelette', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'S\'assurer que le thon est de qualité sashimi. Couper en dés réguliers de 1 cm au couteau (ne jamais hacher). Réserver au frais.' },
      { order: 2, instruction: 'Torréfier les graines de sésame à sec 2 minutes dans une poêle. Laisser refroidir.' },
      { order: 3, instruction: 'Préparer la marinade : mélanger sauce soja, huile de sésame, jus de citron vert et gingembre râpé.' },
      { order: 4, instruction: 'Couper les avocats en dés. Les arroser d\'un filet de citron pour éviter l\'oxydation.' },
      { order: 5, instruction: 'Mélanger délicatement le thon avec la marinade 5 minutes avant le service. Ne pas trop mariner.' },
      { order: 6, instruction: 'Dresser en cercle : base d\'avocat, tartare de thon par-dessus. Parsemer de sésame, ciboulette ciselée et piment d\'Espelette.' },
    ],
    nutrition: { calories: 195, protein: 24, carbs: 4, fat: 10, fiber: 3 },
  },

  'ai-s3': {
    id: 'ai-s3',
    title: 'Salade de mâche grenade',
    description: 'Mâche, grenade, noix, vinaigrette tumérique',
    category: 'starter',
    prepTime: 15,
    cookTime: 0,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'ANTIOXYDANT'],
    tags: ['végétalien', 'sans gluten', 'froid', 'antioxydant'],
    ingredients: [
      { name: 'Mâche', quantity: '400', unit: 'g' },
      { name: 'Grenades', quantity: '3' },
      { name: 'Cerneaux de noix', quantity: '150', unit: 'g' },
      { name: 'Myrtilles fraîches', quantity: '200', unit: 'g' },
      { name: 'Huile d\'olive vierge extra', quantity: '5', unit: 'c. à soupe' },
      { name: 'Vinaigre de cidre', quantity: '2', unit: 'c. à soupe' },
      { name: 'Curcuma', quantity: '1', unit: 'c. à café' },
      { name: 'Miel', quantity: '1', unit: 'c. à café' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Laver et essorer délicatement la mâche. Égrener les grenades.' },
      { order: 2, instruction: 'Casser grossièrement les cerneaux de noix. Les torréfier 3 minutes à sec. Laisser refroidir.' },
      { order: 3, instruction: 'Préparer la vinaigrette tumérique : fouetter l\'huile d\'olive, le vinaigre de cidre, le curcuma, le miel, sel et poivre.' },
      { order: 4, instruction: 'Juste avant le service, mélanger la mâche avec la vinaigrette. Disposer dans les assiettes.' },
      { order: 5, instruction: 'Répartir les graines de grenade, les myrtilles et les noix. Servir immédiatement.' },
    ],
    nutrition: { calories: 165, protein: 4, carbs: 12, fat: 12, fiber: 4 },
  },

  // ─── MENU ANTI-INFLAM — Plats ────────────────────────────────────────────

  'ai-m1': {
    id: 'ai-m1',
    title: 'Saumon avocat quinoa',
    description: 'Saumon sauvage, quinoa noir, avocat, épinards',
    category: 'main',
    prepTime: 15,
    cookTime: 25,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'PROT-BON'],
    tags: ['sans gluten', 'oméga-3', 'chaud'],
    ingredients: [
      { name: 'Filets de saumon sauvage', quantity: '1.5', unit: 'kg' },
      { name: 'Quinoa noir (ou tricolore)', quantity: '600', unit: 'g' },
      { name: 'Avocats', quantity: '5' },
      { name: 'Épinards frais', quantity: '500', unit: 'g' },
      { name: 'Tomates cerises', quantity: '300', unit: 'g' },
      { name: 'Citron', quantity: '3' },
      { name: 'Huile d\'olive', quantity: '3', unit: 'c. à soupe' },
      { name: 'Aneth', quantity: '1', unit: 'bouquet' },
      { name: 'Ail', quantity: '3', unit: 'gousses' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Cuire le quinoa dans 2 fois son volume d\'eau bouillante salée pendant 15 minutes. Égoutter.' },
      { order: 2, instruction: 'Assaisonner les filets de saumon avec sel, poivre et jus de citron. Griller côté peau 4 min, retourner 3 min.' },
      { order: 3, instruction: 'Faire revenir l\'ail émincé dans l\'huile. Ajouter les épinards et faire tomber 2 minutes. Saler.' },
      { order: 4, instruction: 'Couper les avocats en tranches et les tomates cerises en deux. Arroser d\'un filet de citron.' },
      { order: 5, instruction: 'Dresser : lit de quinoa, épinards, saumon, tranches d\'avocat et tomates cerises. Finir avec l\'aneth frais et un zeste de citron.' },
    ],
    nutrition: { calories: 520, protein: 44, carbs: 32, fat: 22, fiber: 8 },
  },

  'ai-m2': {
    id: 'ai-m2',
    title: 'Poulet curcuma légumes colorés',
    description: 'Poulet mariné curcuma-gingembre, légumes colorés',
    category: 'main',
    prepTime: 20,
    cookTime: 30,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'VIANDE-BLANCHE'],
    tags: ['sans gluten', 'anti-inflammatoire', 'chaud'],
    ingredients: [
      { name: 'Cuisses de poulet désossées', quantity: '2', unit: 'kg' },
      { name: 'Curcuma', quantity: '3', unit: 'c. à café' },
      { name: 'Gingembre frais', quantity: '50', unit: 'g' },
      { name: 'Poivrons tricolores', quantity: '4' },
      { name: 'Courgettes', quantity: '3' },
      { name: 'Carottes', quantity: '4' },
      { name: 'Oignons rouges', quantity: '2' },
      { name: 'Ail', quantity: '5', unit: 'gousses' },
      { name: 'Huile de coco', quantity: '3', unit: 'c. à soupe' },
      { name: 'Coriandre fraîche', quantity: '1', unit: 'bouquet' },
      { name: 'Poivre noir', quantity: '1', unit: 'c. à café' },
      { name: 'Sel', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Mélanger curcuma, gingembre râpé, ail écrasé, huile de coco, sel et poivre. Enrober les morceaux de poulet et mariner 1h minimum (idéalement la veille).' },
      { order: 2, instruction: 'Couper tous les légumes en morceaux de taille similaire pour une cuisson homogène.' },
      { order: 3, instruction: 'Chauffer une grande poêle ou wok. Faire dorer le poulet 5 minutes de chaque côté. Réserver.' },
      { order: 4, instruction: 'Dans la même poêle, faire revenir les oignons 3 minutes. Ajouter les carottes et poivrons, cuire 5 minutes à feu vif.' },
      { order: 5, instruction: 'Ajouter les courgettes, remettre le poulet. Couvrir et cuire à feu moyen 15 minutes.' },
      { order: 6, instruction: 'Servir parsemé de coriandre fraîche ciselée. Accompagner de riz basmati ou quinoa si besoin.' },
    ],
    nutrition: { calories: 385, protein: 46, carbs: 15, fat: 16, fiber: 5 },
  },

  'ai-m3': {
    id: 'ai-m3',
    title: 'Bowl végétarien complet',
    description: 'Pois chiches rôtis, patate douce, chou rouge, tahini',
    category: 'main',
    prepTime: 20,
    cookTime: 35,
    servings: 10,
    difficulty: 'easy',
    orientations: ['ANTI-INFLAM', 'PROT-BON'],
    tags: ['végétarien', 'sans gluten', 'récupération'],
    ingredients: [
      { name: 'Pois chiches cuits', quantity: '1.5', unit: 'kg' },
      { name: 'Patates douces', quantity: '2', unit: 'kg' },
      { name: 'Chou rouge', quantity: '1', unit: 'petit' },
      { name: 'Quinoa', quantity: '500', unit: 'g' },
      { name: 'Épinards', quantity: '300', unit: 'g' },
      { name: 'Tahini (purée de sésame)', quantity: '150', unit: 'g' },
      { name: 'Jus de citron', quantity: '3', unit: 'citrons' },
      { name: 'Ail', quantity: '2', unit: 'gousses' },
      { name: 'Cumin', quantity: '2', unit: 'c. à café' },
      { name: 'Paprika fumé', quantity: '2', unit: 'c. à café' },
      { name: 'Huile d\'olive', quantity: '4', unit: 'c. à soupe' },
      { name: 'Graines de tournesol', quantity: '80', unit: 'g' },
    ],
    steps: [
      { order: 1, instruction: 'Préchauffer le four à 220°C. Couper les patates douces en cubes. Égoutter et sécher les pois chiches.' },
      { order: 2, instruction: 'Mélanger les pois chiches avec 2 c. à soupe d\'huile, cumin, paprika, sel. Étaler sur une plaque. Cuire 25 minutes jusqu\'à ce qu\'ils soient croustillants.' },
      { order: 3, instruction: 'Sur une autre plaque, rôtir les patates douces avec huile et sel pendant 30 minutes.' },
      { order: 4, instruction: 'Cuire le quinoa. Émincer finement le chou rouge et le masser avec un peu de sel et citron.' },
      { order: 5, instruction: 'Préparer la sauce tahini : mélanger le tahini avec jus de citron, ail écrasé, eau tiède jusqu\'à consistance crémeuse.' },
      { order: 6, instruction: 'Dresser les bowls : quinoa, épinards frais, patates douces, pois chiches croustillants, chou rouge. Napper de sauce tahini et parsemer de graines.' },
    ],
    nutrition: { calories: 490, protein: 22, carbs: 60, fat: 18, fiber: 14 },
  },

  // ─── MENU MATCH DAY — Entrées ────────────────────────────────────────────

  'md-s1': {
    id: 'md-s1',
    title: 'Riz au lait protéiné',
    description: 'Riz complet, lait d\'amande, cannelle, miel',
    category: 'starter',
    prepTime: 5,
    cookTime: 40,
    servings: 10,
    difficulty: 'easy',
    orientations: ['GLUC-HAUT', 'GROSSE-MAT'],
    tags: ['sans gluten', 'pré-match', 'glucides'],
    ingredients: [
      { name: 'Riz rond complet', quantity: '500', unit: 'g' },
      { name: 'Lait d\'amande', quantity: '2', unit: 'L' },
      { name: 'Protéine whey vanille', quantity: '100', unit: 'g' },
      { name: 'Miel d\'acacia', quantity: '80', unit: 'g' },
      { name: 'Cannelle en poudre', quantity: '2', unit: 'c. à café' },
      { name: 'Vanille en gousse', quantity: '2', unit: 'gousses' },
      { name: 'Bananes', quantity: '5' },
      { name: 'Amandes effilées', quantity: '80', unit: 'g' },
    ],
    steps: [
      { order: 1, instruction: 'Porter le lait d\'amande à frémissement avec les gousses de vanille fendues.' },
      { order: 2, instruction: 'Ajouter le riz, remuer et cuire à feu très doux pendant 35-40 minutes en remuant régulièrement.' },
      { order: 3, instruction: 'Hors du feu, incorporer le miel et la cannelle. Laisser tiédir 10 minutes.' },
      { order: 4, instruction: 'Diluer la protéine whey dans 2 c. à soupe d\'eau froide et incorporer délicatement au riz tiède (ne pas cuire).' },
      { order: 5, instruction: 'Servir en verrines avec des tranches de banane et des amandes effilées torréfiées.' },
    ],
    nutrition: { calories: 290, protein: 14, carbs: 48, fat: 5, fiber: 3 },
  },

  'md-s2': {
    id: 'md-s2',
    title: 'Soupe de légumineuses',
    description: 'Lentilles corail, tomates, épices douces',
    category: 'starter',
    prepTime: 10,
    cookTime: 25,
    servings: 10,
    difficulty: 'easy',
    orientations: ['PROT-BON', 'GROSSE-MAT'],
    tags: ['végétalien', 'sans gluten', 'chaud'],
    ingredients: [
      { name: 'Lentilles corail', quantity: '600', unit: 'g' },
      { name: 'Tomates pelées en boîte', quantity: '2', unit: 'boîtes 400g' },
      { name: 'Oignons', quantity: '2' },
      { name: 'Ail', quantity: '4', unit: 'gousses' },
      { name: 'Cumin moulu', quantity: '2', unit: 'c. à café' },
      { name: 'Coriandre moulue', quantity: '2', unit: 'c. à café' },
      { name: 'Paprika', quantity: '1', unit: 'c. à café' },
      { name: 'Bouillon de légumes', quantity: '2', unit: 'L' },
      { name: 'Huile d\'olive', quantity: '2', unit: 'c. à soupe' },
      { name: 'Coriandre fraîche', quantity: '1', unit: 'bouquet' },
      { name: 'Jus de citron', quantity: '1', unit: 'citron' },
    ],
    steps: [
      { order: 1, instruction: 'Faire revenir l\'oignon émincé dans l\'huile d\'olive à feu moyen 5 minutes. Ajouter l\'ail et les épices, cuire 1 minute.' },
      { order: 2, instruction: 'Rincer les lentilles. Les ajouter avec les tomates et le bouillon. Porter à ébullition.' },
      { order: 3, instruction: 'Réduire à feu doux et cuire 20 minutes jusqu\'à ce que les lentilles soient fondantes.' },
      { order: 4, instruction: 'Mixer partiellement pour une texture mi-lisse mi-rustique. Assaisonner avec jus de citron, sel, poivre.' },
      { order: 5, instruction: 'Servir chaud avec la coriandre fraîche et un filet d\'huile d\'olive.' },
    ],
    nutrition: { calories: 210, protein: 13, carbs: 32, fat: 4, fiber: 8 },
  },

  'md-s3': {
    id: 'md-s3',
    title: 'Tartines complètes œufs pochés avocat',
    description: 'Pain complet, œufs pochés, avocat, graines chia',
    category: 'starter',
    prepTime: 15,
    cookTime: 5,
    servings: 10,
    difficulty: 'medium',
    orientations: ['PROT-BON', 'GLUC-MOD', 'GROSSE-MAT'],
    tags: ['végétarien', 'pré-match'],
    ingredients: [
      { name: 'Pain de seigle complet', quantity: '20', unit: 'tranches' },
      { name: 'Œufs frais', quantity: '20' },
      { name: 'Avocats mûrs', quantity: '6' },
      { name: 'Jus de citron', quantity: '2', unit: 'citrons' },
      { name: 'Graines de chia', quantity: '60', unit: 'g' },
      { name: 'Tomates', quantity: '4' },
      { name: 'Vinaigre blanc', quantity: '2', unit: 'c. à soupe' },
      { name: 'Sel, poivre, piment d\'Espelette', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Écraser les avocats avec le jus de citron, sel et poivre. Réserver.' },
      { order: 2, instruction: 'Faire bouillir une grande casserole d\'eau avec le vinaigre. Réduire à frémissement.' },
      { order: 3, instruction: 'Casser chaque œuf dans un ramequin. Créer un tourbillon dans l\'eau et y glisser l\'œuf. Pocher 3 minutes. Égoutter sur papier absorbant.' },
      { order: 4, instruction: 'Toaster les tranches de pain.' },
      { order: 5, instruction: 'Tartiner généreusement de purée d\'avocat. Disposer les rondelles de tomate, puis l\'œuf poché.' },
      { order: 6, instruction: 'Saupoudrer de graines de chia, piment d\'Espelette et fleur de sel. Servir immédiatement.' },
    ],
    nutrition: { calories: 320, protein: 18, carbs: 30, fat: 14, fiber: 7 },
  },

  // ─── MENU MATCH DAY — Plats ──────────────────────────────────────────────

  'md-m1': {
    id: 'md-m1',
    title: 'Pâtes poulet sauce tomate',
    description: 'Pâtes complètes, blanc de poulet, sauce tomate maison',
    category: 'main',
    prepTime: 15,
    cookTime: 30,
    servings: 10,
    difficulty: 'easy',
    orientations: ['GLUC-HAUT', 'PROT-BON', 'GROSSE-MAT'],
    tags: ['pré-match', 'haute énergie', 'chaud'],
    ingredients: [
      { name: 'Pâtes complètes (spaghetti)', quantity: '1.2', unit: 'kg' },
      { name: 'Blancs de poulet', quantity: '1.5', unit: 'kg' },
      { name: 'Tomates pelées', quantity: '3', unit: 'boîtes 400g' },
      { name: 'Oignons', quantity: '3' },
      { name: 'Ail', quantity: '5', unit: 'gousses' },
      { name: 'Basilic frais', quantity: '1', unit: 'bouquet' },
      { name: 'Origan', quantity: '2', unit: 'c. à café' },
      { name: 'Huile d\'olive', quantity: '3', unit: 'c. à soupe' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive 5 minutes. Ajouter les tomates, origan, sel, poivre. Mijoter 20 minutes.' },
      { order: 2, instruction: 'Couper les blancs de poulet en lanières. Les cuire à feu vif dans une poêle huilée 6-8 minutes jusqu\'à coloration.' },
      { order: 3, instruction: 'Ajouter le poulet à la sauce tomate. Mijoter ensemble 5 minutes.' },
      { order: 4, instruction: 'Cuire les pâtes al dente. Égoutter en conservant 1 verre d\'eau de cuisson.' },
      { order: 5, instruction: 'Mélanger les pâtes avec la sauce. Ajouter un peu d\'eau de cuisson si nécessaire. Servir avec le basilic frais.' },
    ],
    nutrition: { calories: 580, protein: 50, carbs: 70, fat: 8, fiber: 8 },
  },

  'md-m2': {
    id: 'md-m2',
    title: 'Risotto jambon herbes',
    description: 'Riz arborio, jambon blanc, parmesan léger, herbes',
    category: 'main',
    prepTime: 10,
    cookTime: 35,
    servings: 10,
    difficulty: 'medium',
    orientations: ['GLUC-HAUT', 'PROT-BON'],
    tags: ['pré-match', 'chaud', 'glucides'],
    ingredients: [
      { name: 'Riz arborio', quantity: '1', unit: 'kg' },
      { name: 'Jambon blanc tranché épais', quantity: '800', unit: 'g' },
      { name: 'Parmesan allégé', quantity: '150', unit: 'g' },
      { name: 'Bouillon de volaille', quantity: '3', unit: 'L' },
      { name: 'Oignons', quantity: '2' },
      { name: 'Vin blanc sec', quantity: '200', unit: 'ml' },
      { name: 'Persil plat', quantity: '1', unit: 'bouquet' },
      { name: 'Thym frais', quantity: '4', unit: 'branches' },
      { name: 'Beurre allégé', quantity: '40', unit: 'g' },
      { name: 'Huile d\'olive', quantity: '2', unit: 'c. à soupe' },
      { name: 'Sel, poivre', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Maintenir le bouillon chaud dans une casserole à part.' },
      { order: 2, instruction: 'Faire suer les oignons émincés dans l\'huile et le beurre 5 minutes sans coloration.' },
      { order: 3, instruction: 'Ajouter le riz, nacrer 2 minutes en remuant. Déglacer au vin blanc, laisser absorber.' },
      { order: 4, instruction: 'Ajouter le bouillon chaud louche par louche en remuant constamment. L\'absorption doit être complète avant chaque ajout. Cuire 18-20 minutes.' },
      { order: 5, instruction: 'Couper le jambon en dés. L\'ajouter au risotto en fin de cuisson avec le parmesan râpé. Mantecare.' },
      { order: 6, instruction: 'Ajuster la consistance avec le bouillon. Servir immédiatement avec le persil ciselé et le thym.' },
    ],
    nutrition: { calories: 520, protein: 38, carbs: 68, fat: 8, fiber: 2 },
  },

  'md-m3': {
    id: 'md-m3',
    title: 'Burger sport maison',
    description: 'Pain complet, steak haché 5% MG, légumes, sauce yaourt',
    category: 'main',
    prepTime: 20,
    cookTime: 15,
    servings: 10,
    difficulty: 'easy',
    orientations: ['PROT-BON', 'GLUC-HAUT'],
    tags: ['pré-match', 'haute protéine', 'chaud'],
    ingredients: [
      { name: 'Steak haché 5% MG (180g/pers)', quantity: '1.8', unit: 'kg' },
      { name: 'Pains burger complets', quantity: '10' },
      { name: 'Yaourt grec 0%', quantity: '400', unit: 'g' },
      { name: 'Moutarde de Dijon', quantity: '2', unit: 'c. à soupe' },
      { name: 'Tomates', quantity: '4' },
      { name: 'Salade verte', quantity: '1', unit: 'pièce' },
      { name: 'Cornichons', quantity: '200', unit: 'g' },
      { name: 'Oignons rouges', quantity: '2' },
      { name: 'Emmental allégé', quantity: '150', unit: 'g' },
      { name: 'Sel, poivre, paprika', quantity: 'q.s.' },
    ],
    steps: [
      { order: 1, instruction: 'Préparer la sauce yaourt : mélanger yaourt grec, moutarde, cornichons hachés, sel, poivre. Réserver au frais.' },
      { order: 2, instruction: 'Assaisonner le haché avec sel, poivre et paprika. Former des steaks de 180g en appuyant légèrement au centre.' },
      { order: 3, instruction: 'Cuire les steaks à la plancha ou poêle grill très chaude : 3 min de chaque côté pour une cuisson à point. Ajouter le fromage en fin de cuisson.' },
      { order: 4, instruction: 'Toaster les pains burger coupés en deux.' },
      { order: 5, instruction: 'Monter les burgers : sauce sur le pain du bas, salade, tomate, oignon rouge, steak fromage, cornichons, sauce. Fermer.' },
      { order: 6, instruction: 'Servir avec des patates douces au four ou une salade verte.' },
    ],
    nutrition: { calories: 540, protein: 52, carbs: 42, fat: 16, fiber: 5 },
  },
};

export function getRecipe(id: string): Recipe | null {
  return RECIPES[id] ?? null;
}
