-- PARTIE 1 : Enums
CREATE TYPE "UserRole" AS ENUM ('COOK', 'COACH', 'PLAYER', 'NUTRITIONIST');
CREATE TYPE "TrainingSlot" AS ENUM ('MORNING', 'AFTERNOON');
CREATE TYPE "TrainingIntensity" AS ENUM ('LOW', 'MODERATE', 'HIGH');
CREATE TYPE "NutritionalOrientation" AS ENUM ('ANTI_INFLAM', 'GLUC_MOD', 'GLUC_HAUT', 'PROT_BON', 'PROT_MAIGRE', 'ANTIOXYDANT', 'VIANDE_BLANCHE', 'GROSSE_MAT');
CREATE TYPE "MenuCategory" AS ENUM ('STARTER', 'MAIN', 'DESSERT');
CREATE TYPE "RecipeDifficulty" AS ENUM ('EASY', 'MEDIUM', 'HARD');
